#!/usr/bin/env bash
#install nginx and create index.html file with Hello World text

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee file /var/www/html/index.html
host_name="$HOSTNAME" 
sudo service nginx restart
