#!/usr/bin/env bash
#install nginx and create index.html file with Hello World text

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo service nginx restart
