#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee -a /var/www/html/index.nginx-debian.html
sed -i '/listen 80 131224-web-01/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
